#ifndef MANAGEMENTALGORITHM_GLOBAL_H
#define MANAGEMENTALGORITHM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MANAGEMENTALGORITHM_LIBRARY)
#  define MANAGEMENTALGORITHMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MANAGEMENTALGORITHMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MANAGEMENTALGORITHM_GLOBAL_H
